name: design_system
description: A Pilar Mobile Test design_system package.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  core: ^0.0.1
  core_test: ^0.0.1
  flutter:
    sdk: flutter
  i18n: ^0.0.1

dev_dependencies:
  coverage: ^1.8.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
