name: core
description: A Pilar Mobile Test core package.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
