name: network
description: A Pilar Mobile Test network package.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  core: ^0.0.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
